const SHA256 = require('crypto-js/sha256');
const EC = require('elliptic').ec;
// elliptic curve - used in bitcoin as well
const ec = new EC('secp256k1');

/**
 * A transaction which is embedded in a Block
 */
class Transaction {
    /**
     * 
     * @param {String} fromAddress From address
     * @param {String} toAddress Destination address
     * @param {Number} amount Amount of currency
     */
    constructor(fromAddress, toAddress, amount) {
        this.fromAddress = fromAddress;
        this.toAddress = toAddress;
        this.amount = amount;
    }

    /**
     * 
     * @returns SHA256 string which will be the hash of the current block
     */
    calculateHash() {
        return SHA256(this.fromAddress + this.toAddress + this.amount).toString();
    }

    /**
     * Sign the hash of transaction and store in signature
     * @param {String} signingKey The key generated by elliptic curve
     */
    signTransaction(signingKey) {
        if (signingKey.getPublic('hex') !== this.fromAddress) {
            // public key is your wallet address
            throw new Error("You cannot sign transactions for other wallets");
        }
            
        const hashOfTransaction = this.calculateHash();
        // sign transaction
        const signature = signingKey.sign(hashOfTransaction, 'base64');
        this.signature = signature.toDER('hex');
    }

    /**
     * Checks authenticity of a transaction
     * @returns If the transaction is signed by a correct key
     */
    isValid() {
        // allow mining reward transactions
        if (this.fromAddress === null)
            return true;

        if (!this.signature || this.signature.length === 0) {
            throw new Error("No signature in this transaction!");
        }

        // verify if transaction hash is signed by a correct key
        const publicKey = ec.keyFromPublic(this.fromAddress, 'hex');
        return publicKey.verify(this.calculateHash(), this.signature);
    }
}

/**
 * A block on a blockchain
 */
class Block {
    /**
     * 
     * @param {Date} timestamp Block created
     * @param {Object} transactions List of transactions
     * @param {String} previousHash Hash of the previous block
     */
    constructor(timestamp, transactions, previousHash = '') {
        this.timestamp = timestamp;
        this.transactions = transactions;
        this.previousHash = previousHash;
        // hash of this block
        this.hash = this.calculateHash();
        this.nonce = 0;
    }

    /**
     * 
     * @returns SHA256 string which will be the hash of the current block
     */
    calculateHash() {
        return SHA256(this.previousHash + this.timestamp + JSON.stringify(this.transactions) + this.nonce).toString();
    }

    /**
     * Mines a block and verifies if the hash value has the number of zeroes set by difficulty
     * Same method is used in bitcoin mining.
     * @param {int} difficulty Length of characters to be checked
     */
    mineBlock(difficulty) {
        while (this.hash.substring(0, difficulty) !== Array(difficulty + 1).join("0")) {
            this.nonce += 1;
            this.hash = this.calculateHash();
        }

        console.log("Block mined: " + this.hash);
    }

    /**
     * Iterates through the transaction in the block and checks authenticity of the transaction.
     * @returns if the transaction is valid or not
     */
    hasValidTransactions() {
        for (const transaction of this.transactions) {
            if (!transaction.isValid()) {
                return false;
            }
        }

        return true;
    }
}

/**
 * A Blockchain
 */
class Blockchain {
    
    constructor() {
        // initialize the chain with one block
        this.chain = [this.createGenesisBlock()];
        this.difficulty = 2;
        this.pendingTransactions = [];
        this.miningReward = 100;
    }

    /**
     * Creates a first block on the blockchain
     * The first block on a blockchain is called 'Genesis Block'
     */
    createGenesisBlock() {
        return new Block(Date.now(), "Genesis block", "0")
    }

    /**
     * 
     * @returns Last block on the blockchain
     */
    getLatestBlock() {
        return this.chain[this.chain.length - 1];
    }

    /**
     * 
     * @param {Object} newBlock New block to be added
     */
    addBlock(newBlock) {
        // set previous hash to the hash of the last block on the chain
        newBlock.previousHash = this.getLatestBlock().hash;
        // mine block
        newBlock.mineBlock(this.difficulty);
        // push the block to the chain
        this.chain.push(newBlock);
    }

    /**
     * Miner - Validate a set of transactions and allocate them to a block, and in turn earn a reward
     * @param {String} miningRewardAddress Address of the miner's wallet
     */
    minePendingTransactions(miningRewardAddress) {
        const rewardTransaction = new Transaction(null, miningRewardAddress, this.miningReward);
        this.pendingTransactions.push(rewardTransaction);

        let block = new Block(Date.now(), this.pendingTransactions);

        this.addBlock(block);
        
        // this.pendingTransactions = [
        //     new Transaction(null, miningRewardAddress, this.miningReward)
        // ];
        this.pendingTransactions = [];
    }

    /**
     * Adds a transaction to the pending transactions list
     * @param {Transaction} transaction Transaction includes from & to address, amount
     */
    addTransaction(transaction) {
        if (!transaction.fromAddress || !transaction.toAddress) {
            throw new Error("Transaction must include from and to address");
        }

        if (!transaction.isValid()) {
            throw new Error("Transaction is invalid");
        }

        this.pendingTransactions.push(transaction);
    }


    /**
     * Retrieve the balance of the given address
     * @param {String} address Wallet address
     * @returns Balance amount
     */
    getBalanceOfAddress(address) {
        let balance = 0;

        for (const block of this.chain) {
            for (const transaction of block.transactions) {
                if (transaction.fromAddress === address) {
                    balance -= transaction.amount;
                }

                if (transaction.toAddress === address) {
                    balance += transaction.amount;
                }
            }
        }

        return balance;
    }

    /**
     * A block should not be modified without invalidating rest of the chain
     * @returns true if data in every block is not tampered.
     */
    isChainValid() {
        // loop through the chain, avoid i = 0, since it's a genesis block
        for (let i = 1; i < this.chain.length; i += 1) {
            const currentBlock = this.chain[i];
            const previousBlock = this.chain[i-1];

            // checks for authenticity of transactions of current block
            if (!currentBlock.hasValidTransactions()) {                
                return false;
            }

            // Re-calculate hash. The hash value would be changed if any data is tampered.
            if (currentBlock.hash !== currentBlock.calculateHash()) {                
                return false;
            }

            // check if previous hash is accurate
            if (currentBlock.previousHash !== previousBlock.hash) {
                console.log("currentBlock.previousHash: " + currentBlock.previousHash);
                console.log("\npreviousBlock.hash: " + previousBlock.hash);
                console.log("\ni: " + i)
                return false;
            }
            
            return true;
        }
    }
}

module.exports.Blockchain = Blockchain;
module.exports.Transaction = Transaction;